image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x64
  - x86
environment:
  matrix:
#    - generator: mingw-w64
    - generator: vs2017

matrix:
  fast_finish: true

for:
  - matrix:
      only:
        - generator: vs2017
    install:
      - git submodule update --init
      - cinst nasm
      - cinst nsis -pre
      - appveyor DownloadFile https://download.tsi.telecom-paristech.fr/gpac/gpac_extra_libs.zip -FileName extra_libs.zip
      - unzip extra_libs.zip
      - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%
    before_build:
      - msbuild gpac_extra_libs\build\msvc\BuildAll_vc10.sln /t:Build  /p:Configuration=Release
      - dir gpac_extra_libs\lib\win32\release
      - gpac_extra_libs\CopyLibs2Public.bat all
      - version.bat
    build:
      project: build/msvc14/gpac.sln
      parallel: true
    after_build:
      - gpac_public\generate_installer.bat







#artifacts:
#  - path: bin\
#    name: $(APPVEYOR_PROJECT_NAME)
#  - path: bin\
#    name: $(APPVEYOR_PROJECT_NAME)

#deploy:
#  - provider: GitHub
#    artifact: $(APPVEYOR_PROJECT_NAME)
#    auth_token:
#      secure: 'sf0pQXlPI+X6LoAR8QUJB74jjzNxcLGOXI3H0nbxJq8llvGPG/TAUd87hq5iHZXo'
#    prerelease: true
#    on:
#      appveyor_repo_tag: true
