language: c
dist: xenial
os:
  - linux
  - osx
cache: ccache
addons:
  apt:
    update: true
    packages:
      - debhelper
      - devscripts
      - dvb-apps
      - fakeroot
      - lcov
      - lib{a52-0.7.4,asound2,av{codec,device,format,util},faad,gl1-mesa,jack,jpeg62,mad0,mozjs185,ogg,openjpeg,pulse,sdl1.2,ssl,swscale,theora,vorbis,xv{,idcore}}-dev
      - libavcodec-extra
      - linux-sound-base
      - mesa-utils
      - x11proto-{gl,video}-dev
  homebrew:
    update: true
    packages:
      - faad2
      - ffmpeg
      - gnu-time
      - gnu-sed
      - gnu-tar
      - lcov
      - libmad
      - sdl
      - spidermonkey
env:
  - GPAC_CONFIGURE_OPTIONS="--prefix=build/mp4box --enable-debug --static-mp4box" DOINSTALL="make install"
  - GPAC_CONFIGURE_OPTIONS="--enable-debug --static-modules"
  - GPAC_CONFIGURE_OPTIONS="--enable-debug --enable-static-bin"
matrix:
  include:
    - os: osx
      env: GPAC_CONFIGURE_OPTIONS="--enable-mem-track" DOINSTALL="sudo make install" AUDIODEV=null
    - os: windows
      env: GPAC_CONFIGURE_OPTIONS="--{build,host,target}=x86_64-w64-mingw32 --disable-shared --enable-static --enable-debug --static-mp4box --cross-prefix=x86_64-w64-mingw32-"
      #--prefix=build/x86_64-w64-mingw32 --enable-debug --static-mp4box --use-zlib=no --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --extra-ldflags=-Lbuild/x86_64-w64-mingw32/lib" GPAC_CONFIGURE_ECFLAGS="-Ibuild/x86_64-w64-mingw32/include -w -fPIC"
    - os: windows
      env: GPAC_CONFIGURE_OPTIONS="--{build,host,target}=i686-w64-mingw32 --disable-shared --enable-static --enable-debug --static-mp4box --cross-prefix=i686-w64-mingw32-
      #--prefix=build/x86_64-w64-mingw32 --enable-debug --static-mp4box --use-zlib=no --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --extra-ldflags=-Lbuild/x86_64-w64-mingw32/lib" GPAC_CONFIGURE_ECFLAGS="-Ibuild/x86_64-w64-mingw32/include -w -fPIC"
    - services:
        - xvfb
      before_script:
        - sleep 3 # give xvfb some time to start
        - glxinfo # check glx status
      env: GPAC_CONFIGURE_OPTIONS="--enable-mem-track --enable-gcov" DOINSTALL="sudo make install" DOTRAVIS="make travis" AUDIODEV=null
    - env: GPAC_CONFIGURE_OPTIONS="--prefix=build/all --enable-debug --disable-all" DOINSTALL="sudo make install"
    - env: GPAC_CONFIGURE_OPTIONS="--enable-debug --use-{js,mad,xvid,ogg,vorbis,theora,openjpeg,a52}=no --disable-{streaming,isoff-frag,isoff-hint,isoff-write,loader-xmt,loader-bt,loader-isoff,scene-encode,mcrypt,od-dump,scene-dump,scene-stats,swf,export,import,m2ps,ogg,qtvr,seng,smgr,x3d,3d,ssl,jack,pulse,odf,isoff,m2ts-mux,dvbx,saf,vobsub,ttxt,od-parse,atsc,avi}"

script:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install msys2; choco uninstall mingw; fi
  - echo $PATH
  - if [ $TRAVIS_OS_NAME = windows ]; then echo -e "$msys2=\"C:\\tools\\msys64\"\n$env:Path = \"$msys2\\mingw64\\bin;$msys2\\usr\\local\\bin;$msys2\\usr\\bin\"\n$configureopt = @(\"-lc ./configure --extra-cflags=$env:GPAC_CONFIGURE_ECFLAGS $env:GPAC_CONFIGURE_OPTIONS\".Split(' '))\nStart-Process -NoNewWindow -Wait -FilePath \"$msys2\\usr\\bin\\bash.exe\" -WorkingDirectory $env:TRAVIS_BUILD_DIR -ArgumentList $configureopt\nStart-Process -NoNewWindow -Wait -FilePath \"$msys2\\usr\\bin\\bash.exe\" -WorkingDirectory $env:TRAVIS_BUILD_DIR -ArgumentList \"make\",\"-j$(nproc)\"" > $TRAVIS_BUILD_DIR\bash.ps1 ; powershell -noprofile -executionpolicy bypass $env:TRAVIS_BUILD_DIR\\bash.ps1; else ./configure --extra-cflags=''"$GPAC_CONFIGURE_ECFLAGS"'' $GPAC_CONFIGURE_OPTIONS; make -j$(if [ $TRAVIS_OS_NAME = osx ]; then sysctl -n hw.ncpu; else nproc; fi); fi
  - $DOINSTALL
  - $DOTRAVIS
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
    recipients:
      - travisci@gpac.io
