language: c
compiler:
  - clang
  - gcc
dist: xenial
os:
  - linux
  - osx
cache: ccache
addons:
  apt:
    packages:
    - binutils-mingw-w64-{i686,x86-64}
    - debhelper
    - devscripts
    - dvb-apps
    - fakeroot
    - g{cc,++}-mingw-w64-{i686,x86-64}
    - lcov
    - lib{a52-0.7.4,asound2,av{codec,device,format,util},faad,freetype6,gl1-mesa,jack,jpeg62,mad0,mozjs185,ogg,openjpeg,png12,pulse,sdl1.2,ssl,swscale,theora,vorbis,xv{,idcore}}-dev
    - libavcodec-extra
    - linux-sound-base
    - mesa-utils
    - mingw-w64-x86-64-dev
    - pkg-config
    - time
    - x11proto-{gl,video}-dev
    - zlib1g-dev
  homebrew:
    packages:
    - faad2
    - ffmpeg
    - freetype
    - gnu-{time,sed,tar}
    - lcov
    - lib{mad,ogg,vorbis}
    - openjpeg
    - sdl
    - spidermonkey
    - theora
    - xvid
    - xz
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y update -qq ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
env:
  - GPAC_CONFIGURE_OPTIONS="--prefix=build/mp4box --enable-debug --static-mp4box" DOINSTALL="make install"
  - GPAC_CONFIGURE_OPTIONS="--enable-debug --static-modules"
  - GPAC_CONFIGURE_OPTIONS="--enable-{debug,static-bin}"
matrix:
  include:
    - os: osx
      env: GPAC_CONFIGURE_OPTIONS="--enable-mem-track" DOINSTALL="sudo make install" AUDIODEV=null
    - os: linux
      before_script:
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
        - glxinfo # check glx status
      env: GPAC_CONFIGURE_OPTIONS="--enable-{mem-track,gcov}" DOINSTALL="sudo make install" DOTRAVIS="make travis" AUDIODEV=null DISPLAY=:99.0
    - os: linux
      env: GPAC_CONFIGURE_OPTIONS="--prefix=build/x86_64-w64-mingw32 --enable-debug --static-mp4box --use-zlib=no --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --extra-ldflags=-Lbuild/x86_64-w64-mingw32/lib" GPAC_CONFIGURE_ECFLAGS="-Ibuild/x86_64-w64-mingw32/include -w -fPIC"
    - os: linux
      env: GPAC_CONFIGURE_OPTIONS="--prefix=build/x86_64-w64-mingw32 --enable-debug --static-mp4box --use-zlib=no --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --extra-ldflags=-Lbuild/x86_64-w64-mingw32/lib" GPAC_CONFIGURE_ECFLAGS="-Ibuild/x86_64-w64-mingw32/include -w -fPIC"
    - os: linux
      env: GPAC_CONFIGURE_OPTIONS="--prefix=build/all --enable-debug --disable-all" DOINSTALL="make install"
    - os: linux
      env: GPAC_CONFIGURE_OPTIONS="--enable-debug --use-{js,mad,xvid,ogg,vorbis,theora,openjpeg,a52}=no --disable-{streaming,isoff-frag,isoff-hint,isoff-write,loader-xmt,loader-bt,loader-isoff,scene-encode,mcrypt,od-dump,scene-dump,scene-stats,swf,export,import,m2ps,ogg,qtvr,seng,smgr,x3d,3d,ssl,jack,pulse,odf,isoff,m2ts-mux,dvbx,saf,vobsub,ttxt,od-parse,atsc,avi}"
script:
  - ./configure --extra-cflags=''"$GPAC_CONFIGURE_ECFLAGS"'' $GPAC_CONFIGURE_OPTIONS && make && $DOINSTALL && $DOTRAVIS
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
    recipients:
      - travisci@gpac.io